sudo: required
services:
- docker
#env:
#- COMPOSE_FILE=docker-compose.yml:docker-compose.yml
#before_install:
#- openssl aes-256-cbc -K $encrypted_35b262dc7ab4_key -iv $encrypted_35b262dc7ab4_iv
#  -in .travis/deploy.key.enc -out .travis/deploy.key -d
#- chmod +x ./deploy.sh
#- eval "$(ssh-agent -s)"
#- chmod 600 .travis/deploy.key
#- ssh-add .travis/deploy.key
#- ssh-keyscan service.ceylonapp.com >> ~/.ssh/known_hosts
#- git remote add deploy dokku@service.ceylonapp.com:aiaas
#- git config --global push.default simple
script:
#- ls -lah
- docker build -t ceylonapp/fx-agent-engine .
deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: master